#!/bin/bash

umask 022

# Update repositories
apt-get update

# Install git and ansible
apt-get install ansible git python3 python3-pip python3-apt sudo -y

python3 -m pip install --upgrade pip

if [[ ! -f ~/.vault-password ]]; then
    read -rsp "Please enter the vault-password:" VAULT_PASS < /dev/tty
    echo -e "\n"

    touch ~/.vault-password
    chmod 600 ~/.vault-password
    echo "$VAULT_PASS" > ~/.vault-password
fi

ansible-pull -U https://github.com/ronmckay/ansible-config --checkout main --vault-password-file=~/.vault-password local.yml
