---
- hosts: all
  pre_tasks:
    - include_tasks: tasks/pre_tasks.yml
      tags: always

  roles:
    - common

- hosts: workstations
  gather_facts: no

  roles:
    - workstation

- hosts: taskserver
  gather_facts: no

  tasks:
  - name: Include software from workstation role
    include_role:
      name: workstation
      tasks_from: "{{ item }}"
    loop:
      - software/syncthing.yml
      - software/taskwarrior.yml
      - software/vit.yml

  - name: Configure taskwarrior for user taskwarrior
    include_role:
      name: workstation
      tasks_from: config/taskwarrior-config.yml
    vars:
      config_user: taskwarrior
      user_group: taskwarrior
    tags: tw

  - name: Configure taskwarrior for user poberdie
    include_role:
      name: workstation
      tasks_from: config/taskwarrior-config.yml
    vars:
      config_user: poberdie
      user_group: poberdie
    tags: tw