---
- name: "Include user vars"
  include_vars: "{{ user_vars_file }}"
  when: user_vars_file is defined

- name: "Create user account"
  become: true
  user:
    name: "{{ config_user }}"
    append: yes
    groups: "{{ user_groups if user_groups is defined else (getent_passwd.get('poberdie')[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else 'poberdie') }}"
    system: "{{ is_system_user | default('no') }}"
    password: "{{ default_password | string | password_hash('sha512') }}"
    update_password: "on_create"
  when: ansible_distribution in ["Debian", "Ubuntu"]