---
- include_vars: users/poberdie_vars.yml

- name: poberdie | Configure taskwarrior
  include_tasks: config/taskwarrior-config.yml

- name: poberdie | Install packages for python development
  include_tasks: config/python-dev.yml

# TODO: Add .profile/.zprofile template for WSL distros without services (syncthing)
