---
- include_vars: users/poberdie_vars.yml

- name: poberdie | Configure taskwarrior
  include_tasks: config/taskwarrior-config.yml

- name: poberdie | Install packages for python development
  include_tasks: config/python-dev.yml

- name: poberdie | Restart syncthing service if installation changed
  systemd:
    name: "syncthing@poberdie"
    state: restarted
  when: (syncthing_service.changed | default(false) or syncthing_install.changed | default(false)) and ansible_distribution in ["Debian", "Ubuntu"] and not in_wsl
  become: true

- name: poberdie | Ensure syncthing service is running
  systemd:
    name: "syncthing@poberdie"
    state: started
    enabled: yes
  when: ansible_distribution in ["Debian", "Ubuntu"] and not in_wsl
