---
- block:
    - name: synth-shell | Check if synth-shell is already installed
      stat:
        path: "/home/{{ config_user }}/.config/synth-shell"
      register: synth_shell

    # Install synth-shell if not existend
    - block:
        - name: synth-shell | Clone repository
          git:
            repo: "https://github.com/andresgongora/synth-shell.git"
            dest: "/tmp/ansible-pull-synth-shell"
            depth: 1
            version: "e2613ef017bf47ed43c5c8222b1e97784678182d"

        - name: synth-shell | Run setup
          shell:
            cmd: "echo 'iunynnn' | ./setup.sh"
            chdir: "/tmp/ansible-pull-synth-shell"

        - name: synth-shell | Remove synth-shell repo clone
          file:
            path: "/tmp/ansible-pull-synth-shell"
            state: absent
      when: not synth_shell.stat.exists

    - name: synth-shell | Check if powerline-fonts are installed
      shell: "fc-list | grep 'Hack' | wc -l"
      register: powerline_fonts
      changed_when: false

    # Install powerline-fonts
    - block:
        - name: synth-shell | Clone powerline-fonts
          git:
            repo: "https://github.com/powerline/fonts.git"
            dest: "/tmp/ansible-clone-powerline-fonts"
            depth: 1

        - name: synth-shell | Install powerline-fonts
          shell:
            cmd: "./install.sh"
            chdir: "/tmp/ansible-clone-powerline-fonts"

        - name: synth-shell | Remove powerline-fonts repo clone
          file:
            path: "/tmp/ansible-clone-powerline-fonts"
            state: absent
      when: powerline_fonts.stdout == '0'

    - name: synth-shell | Copy synth-shell config file
      copy:
        src: "synth-shell-prompt.config"
        dest: "/home/{{ config_user }}/.config/synth-shell/synth-shell-prompt.config"
        owner: "{{ config_user }}"
        group: "{{ user_group | default(config_user) }}"
        mode: 0644

  become_user: "{{ config_user }}"
  become: true
  tags: shell,synth-shell
