---
- name: tmux | Copy configuration template
  template:
    src: "users/poberdie/tmux.conf.j2"
    dest: "$HOME/.tmux.conf"
    owner: "{{ config_user }}"
    group: "{{ user_group if user_group is defined else (getent_passwd.get(config_user)[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else config_user) }}"
    mode: 0644
  become: true
  become_user: "{{ config_user }}"
