---
- include_vars: users/poberdie_vars.yml

- block:
    - name: poberdie | Set bash as default shell
      tags: shell,bash
      shell: 'chsh -s $(which bash) poberdie'
      become: true
      become_user: root
      changed_when: false
      failed_when: false

    - name: poberdie | Configure synth-shell
      include_tasks: config/synth-shell.yml

    # Shell and environment variables
    - name: poberdie | Copy shell dotfile templates
      tags: shell,dotfiles
      template:
        src: "{{ item.src  }}"
        dest: "{{ item.dest }}"
        owner: poberdie
        group: "{{ user_group if user_group is defined else (getent_passwd.get('poberdie')[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else 'poberdie') }}"
        mode: 0600
      loop:
        - { src: 'users/poberdie/shell/shrc.j2', dest: '/home/poberdie/.shrc' }
        - { src: 'users/poberdie/shell/sh_aliases.j2', dest: '/home/poberdie/.sh_aliases' }
        - { src: 'users/poberdie/shell/sh_environment.j2', dest: '/home/poberdie/.sh_environment' }
        - { src: 'users/poberdie/shell/bashrc.j2', dest: '/home/poberdie/.bashrc' }

    - name: poberdie | Copy .profile if in WSL environment
      tags: shell,dotfiles
      template:
        src: "users/poberdie/shell/profile.j2"
        dest: "/home/poberdie/.profile"
        owner: poberdie
        group: "{{ user_group if user_group is defined else (getent_passwd.get('poberdie')[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else 'poberdie') }}"
        mode: 0600
      when: in_wsl

    - name: poberdie | ssh | Ensure directory '.ssh' exists
      tags: ssh
      file:
        path: '/home/poberdie/.ssh'
        state: directory
        owner: poberdie
        group: "{{ user_group if user_group is defined else (getent_passwd.get('poberdie')[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else 'poberdie') }}"
        mode: 0755

    # SSH config file
    - name: poberdie | ssh | Copy ssh config template
      tags: ssh
      template:
        src: users/poberdie/ssh/ssh_config.j2
        dest: "/home/poberdie/.ssh/config"
        owner: poberdie
        group: "{{ user_group if user_group is defined else (getent_passwd.get('poberdie')[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else 'poberdie') }}"
        mode: 0600

    # Git config files
    - name: poberdie | git | Copy git config templates
      tags: utilities,git,dotfiles
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: poberdie
        group: "{{ user_group if user_group is defined else (getent_passwd.get('poberdie')[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else 'poberdie') }}"
        mode: 0644
      loop:
        - { src: 'users/poberdie/git/gitconfig.j2', dest: '/home/poberdie/.gitconfig' }
        - { src: 'users/poberdie/git/gitignore.j2', dest: '/home/poberdie/.gitignore' }
        - { src: 'users/poberdie/git/gitmessage.j2', dest: '/home/poberdie/.gitmessage' }

    # Configure tmux
    - name: poberdie | tmux | Configure tmux
      include_tasks: config/tmux-config.yml

    # Configure wsl2-ssh-pageant.exe
    - name: poberdie | ssh | Configure wsl2-ssh-pageant.exe
      include_tasks: config/wsl2-ssh-pageant.yml

    # Vim config and plugins
    - block:
        - name: poberdie | vim/neovim | Ensure necessary directories exist
          file:
            path: "{{ item }}"
            state: directory
            owner: poberdie
            group: "{{ user_group if user_group is defined else (getent_passwd.get('poberdie')[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else 'poberdie') }}"
            mode: 0755
          loop:
            - '/home/poberdie/.config/nvim/after/ftplugin'
            - '/home/poberdie/.config/nvim/ftplugin'
            - '/home/poberdie/.config/nvim/plugins'
            - '/home/poberdie/.vim/after/ftplugin'
            - '/home/poberdie/.vim/autoload'

        - name: poberdie | vim/neovim | Copy vimrr, init.vim and all config directories
          tags: dotfiles
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: poberdie
            group: "{{ user_group if user_group is defined else (getent_passwd.get('poberdie')[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else 'poberdie') }}"
            mode: 0644
          loop:
            - { src: 'users/poberdie/vim/init.vim', dest: '/home/poberdie/.config/nvim/init.vim' }
            - { src: 'users/poberdie/vim/after', dest: '/home/poberdie/.config/nvim' }
            - { src: 'users/poberdie/vim/ftplugin', dest: '/home/poberdie/.config/nvim' }
            - { src: 'users/poberdie/vim/plugins', dest: '/home/poberdie/.config/nvim' }
            - { src: 'users/poberdie/vim/UltiSnips', dest: '/home/poberdie/.config/nvim' }
            - { src: 'users/poberdie/vim/vimrc', dest: '/home/poberdie/.vimrc' }
            - { src: 'users/poberdie/vim/after', dest: '/home/poberdie/.vim' }
            - { src: 'users/poberdie/vim/ftplugin', dest: '/home/poberdie/.vim' }

        - name: poberdie | nvim | Update nvim plugins
          shell: nvim +'silent! PlugUpdate' +qa
          changed_when: false
          failed_when: false

        - name: poberdie | nvim | Clean nvim plugins
          shell: nvim +'silent! PlugClean!' +qa
          changed_when: false
          failed_when: false

        - name: poberdie | nvim | Install nvim plugins
          shell: nvim +'silent! PlugInstall' +qa
          changed_when: false
          failed_when: false

        - name: poberdie | nvim | Install vimwiki_markdown
          pip:
            name: vimwiki_markdown
            state: latest
            umask: "0022"

      tags: utilities,vim,nvim

  when: ansible_distribution in ["Debian", "Ubuntu"]
  become_user: poberdie
  become: true
