---
# This file builds taskwarrior from source if not the requested version
- name: taskwarrior | Check if taskwarrior is installed
  tags: tw
  stat:
    path: "{{ tw_path }}"
  register: tw_binary

- name: taskwarrior | Check taskwarrior version
  tags: tw
  shell: 'echo "yes" | {{ tw_path }} _version | sed "s/.*(\([^)]*\)).*/\1/g"'
  register: tw_commit_id
  when: tw_binary.stat.exists
  changed_when: false
  failed_when: false

- block:
    - name: taskwarrior | Install dependencies for build
      apt:
        name:
          - build-essential
          - git
          - cmake
          - make
          - gcc
          - uuid-dev
          - gnutls-dev

    - name: taskwarrior | Pull taskwarrior repository
      git:
        repo: 'https://github.com/GothenburgBitFactory/taskwarrior.git'
        dest: '/tmp/ansible-pull-taskwarrior'
        depth: 1
        version: "{{ tw_expected_commit_id }}"

    - name: taskwarrior | Run cmake
      shell:
        cmd: 'cmake -DCMAKE_BUILD_TYPE=release .'
        chdir: '/tmp/ansible-pull-taskwarrior/'

    - name: taskwarrior | Run make
      shell:
        cmd: 'make'
        chdir: '/tmp/ansible-pull-taskwarrior/'

    - name: taskwarrior | Run make install
      shell:
        cmd: 'make install'
        chdir: '/tmp/ansible-pull-taskwarrior/'

    - name: taskwarrior | Remove repo clone
      file:
        path: '/tmp/ansible-pull-taskwarrior/'
        state: absent

  when: "(not tw_binary.stat.exists or tw_commit_id is not defined or tw_commit_id.stdout != tw_expected_commit_id) and ansible_distribution in ['Debian', 'Ubuntu']"
  tags: tw
  become: true
