---
- include_vars: taskwarrior_vars.yml

- name: "vit | Ensure '/home/{{ config_user | default('poberdie') }}/.vit' exists"
  tags: tw,vit
  file:
    path: "/home/{{ config_user | default('poberdie') }}/.vit"
    state: directory
    mode: 0755
    owner: "{{ config_user | default('poberdie') }}"
    group: "{{ user_group | default('poberdie') }}"

- name: "vit | Copy vit configuration template"
  tags: tw,vit
  template:
    src: "taskwarrior/vit-config.ini.j2"
    dest: "/home/{{ config_user | default('poberdie') }}/.vit/config.ini"
    owner: "{{ config_user | default('poberdie') }}"
    group: "{{ user_group | default('poberdie') }}"
    mode: 0644

- name: "tw | Ensure '/home/{{ config_user | default('poberdie') }}/.task' exists"
  tags: tw
  file:
    path: "/home/{{ config_user | default('poberdie') }}/.task"
    state: directory
    mode: 0700
    owner: "{{ config_user | default('poberdie') }}"
    group: "{{ user_group | default('poberdie') }}"

- name: "tw | Copy taskwarrior files"
  tags: tw
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ config_user | default('poberdie') }}"
    group: "{{ user_group | default('poberdie') }}"
    mode: 0600
  loop:
    - { src: "taskwarrior/ca.cert.pem", dest: "/home/{{ config_user | default('poberdie') }}/.task/ca.cert.pem" }
    - { src: "taskwarrior/philipp_oberdiek.cert.pem", dest: "/home/{{ config_user | default('poberdie') }}/.task/philipp_oberdiek.cert.pem" }
    - { src: "taskwarrior/philipp_oberdiek.key.pem", dest: "/home/{{ config_user | default('poberdie') }}/.task/philipp_oberdiek.key.pem" }
    - { src: "taskwarrior/hooks", dest: "/home/{{ config_user | default('poberdie') }}/.task/hooks" }
    - { src: "taskwarrior/dark-gray-blue-256.theme", dest: "/home/{{ config_user | default('poberdie') }}/.task/dark-gray-blue-256.theme" }

- name: "tw | Copy .taskrc template"
  tags: tw
  template:
    src: "taskwarrior/taskrc.j2"
    dest: "/home/{{ config_user | default('poberdie') }}/.taskrc"
    owner: "{{ config_user | default('poberdie') }}"
    group: "{{ user_group | default('poberdie') }}"
    mode: 0600

- name: "tw | Sync with taskd server"
  command: "task sync"
  become_user: "{{ config_user | default('poberdie') }}"
  become: true
  changed_when: false

- name: "tw | Install python-dateutil for taskwarrior hooks"
  tags: tw
  pip:
    name: python-dateutil
    state: latest
    umask: '0022'