---
- include_vars: taskwarrior_vars.yml

- block:
    - name: "vit | Ensure '.vit' folder exists"
      file:
        path: "$HOME/.vit"
        state: directory
        mode: 0755
        owner: "{{ config_user }}"
        group: "{{ user_group if user_group is defined else (getent_passwd.get(config_user)[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else config_user) }}"

    - name: "vit | Copy vit configuration template"
      template:
        src: "taskwarrior/vit-config.ini.j2"
        dest: "$HOME/.vit/config.ini"
        owner: "{{ config_user }}"
        group: "{{ user_group if user_group is defined else (getent_passwd.get(config_user)[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else config_user) }}"
        mode: 0644
  tags: vit,tw
  become: true
  become_user: "{{ config_user }}"

- block:
    - name: "tw | Ensure '$HOME/.task' and '$HOME/.task/hooks' exists and have correct permissions"
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: 0700
        owner: "{{ config_user }}"
        group: "{{ user_group if user_group is defined else (getent_passwd.get(config_user)[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else config_user) }}"
      loop:
        - { path: "$HOME/.task/hooks", state: "directory" }
        - { path: "$HOME/.task", state: "touch" }
        - { path: "$HOME/.task/hooks", state: "touch" }

    - name: "tw | Copy taskwarrior files"
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ config_user }}"
        group: "{{ user_group if user_group is defined else (getent_passwd.get(config_user)[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else config_user) }}"
        mode: 0600
      loop:
        - { src: "taskwarrior/ca.cert.pem", dest: "$HOME/.task/ca.cert.pem" }
        - { src: "taskwarrior/philipp_oberdiek.cert.pem", dest: "$HOME/.task/philipp_oberdiek.cert.pem" }
        - { src: "taskwarrior/philipp_oberdiek.key.pem", dest: "$HOME/.task/philipp_oberdiek.key.pem" }
        - { src: "taskwarrior/dark-gray-blue-256.theme", dest: "$HOME/.task/dark-gray-blue-256.theme" }

    - name: "tw | Copy .taskrc template"
      template:
        src: "taskwarrior/taskrc.j2"
        dest: "$HOME/.taskrc"
        owner: "{{ config_user }}"
        group: "{{ user_group if user_group is defined else (getent_passwd.get(config_user)[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else config_user) }}"
        mode: 0600

    - name: "tw | Sync with taskd server"
      command: "task sync"
      changed_when: false

    - name: "tw | Install tasklib for hooks"
      pip:
        name: git+https://github.com/GothenburgBitFactory/tasklib.git@develop
        umask: '0022'

    - name: "tw | Install taskpirate"
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        owner: "{{ config_user }}"
        group: "{{ user_group if user_group is defined else (getent_passwd.get(config_user)[2] if getent_passwd is defined and getent_passwd.get('poberdie', '') != '' else config_user) }}"
        mode: 0744
      loop:
        - { url: "https://raw.githubusercontent.com/tbabej/taskpirate/master/on-add-pirate", dest: "$HOME/.task/hooks/on-add-pirate" }
        - { url: "https://raw.githubusercontent.com/tbabej/taskpirate/master/on-modify-pirate", dest: "$HOME/.task/hooks/on-modify-pirate" }

    - name: "tw | Install hooks"
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        force: yes
      loop:
        - { repo: "https://github.com/tbabej/task.shift-recurrence.git", dest: "$HOME/.task/hooks/shift-recurrence" }
        - { repo: "https://github.com/RonMcKay/task.default-date-time.git", dest: "$HOME/.task/hooks/default-date-time" }

  become_user: "{{ config_user }}"
  become: true
  tags: tw